spring.application.name=track_workout
spring.h2.console.enabled=true
spring.datasource.generate-unique-name=false
spring.datasource.name=db_workouts
spring.sql.init.mode=always

logging.level.org.springframework.jdbc=DEBUG

db.url=${AZURE_DB_URL}
db.user=${AZURE_DB_USER}
db.password=${AZURE_DB_PASSWORD}