name: CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  language-name: "temurin"

jobs:
  get-java-lts:
    name: Get LTS for Java
    runs-on: ubuntu-slim
    outputs:
      lts_versions_fetched: ${{ steps.getJavaVersion.outputs.lts_versions }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get LTS for Java Temurin JDK
        uses: paulie-of-punskas/get-lts-versions@ecb5fdacd088858ba095f069e77b31f5048ccf13 # v1.0.4
        id: getJavaVersion
        with:
          language: ${{ env.language-name }}
          versions_to_fetch: "3"

      - name: Print returned values
        id: outputJavaVersion
        shell: bash
        run: |
          echo "Fetched LTS versions: ${{ steps.getJavaVersion.outputs.lts_versions }}"

  setup-java-environment:
    name: Setup environment
    runs-on: ubuntu-22.04
    needs: get-java-lts
    strategy:
      matrix:
        lts_java_version: ${{ fromJson(needs.get-java-lts.outputs.lts_versions_fetched) }}
    steps:
      - name: Set up latest JDK for x64
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: ${{ matrix.lts_java_version }}
          distribution: ${{ env.language-name }}
          architecture: x64
